[workspace]
resolver = "1"
members = [
	"rpc",
	"node",
	"primitives",
	"runtime/common",
	"runtime/selendra",
	"runtime/selendra/constants",
	"pallets/precompiles/*",
	"pallets/custom-signatures"
]

exclude = [
	"frontier"
]

[profile.release]
# Selendra runtime requires unwinding.
panic = "unwind"
opt-level = 3

# make sure dev builds with backtrace do
# not slow us down
[profile.dev.package.backtrace]
inherits = "release"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1

[profile.testnet]
inherits = "release"
debug = 1 # debug symbols are useful for profilers
debug-assertions = true
overflow-checks = true
