[package]
name = "pallet-evm-precompile-batch"
description = "A Precompile to batch multiple calls."
version = "0.1.0"
edition = "2021"
authors = ["Stake Technologies <devops@stake.co.jp>"]
homepage = "https://astar.network"
repository = "https://github.com/AstarNetwork/Astar"

[dependencies]
log = { version = "0.4.17", default-features = false }
num_enum = { version = "0.5.3", default-features = false }
paste = "1.0.6"
slices = "0.2.0"

# Moonbeam
precompile-utils = { path = "../utils", default-features = false }

# Substrate
parity-scale-codec = { version = "3.6.1", default-features = false, features = ["max-encoded-len"] }

frame-support = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", default-features = false }

# Frontier
evm = { git = "https://github.com/rust-blockchain/evm", rev = "b7b82c7e1fc57b7449d6dfa6826600de37cc1e65", default-features = false, features = ["with-codec"] }
fp-evm = { git = "https://github.com/polkadot-evm/frontier", branch = "polkadot-v1.1.0", default-features = false }
pallet-evm = { git = "https://github.com/polkadot-evm/frontier", branch = "polkadot-v1.1.0", default-features = false }

[dev-dependencies]
derive_more = { version = "0.99" }
hex-literal = "0.4.1"
serde = { version = "1.0.151", features = ["derive"] }
sha3 = { version = "0.10.1", default-features = false }

pallet-balances = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", features = ["std"] }
pallet-timestamp = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.1.0", features = ["std"] }
parity-scale-codec = { version = "3.6.1", features = ["max-encoded-len", "std"] }
precompile-utils = { path ="../utils", features = ["std", "testing"] }
scale-info = { version = "2.5.0", features = ["derive", "std"] }


[features]
default = ["std"]
std = [
	"fp-evm/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-evm/std",
	"parity-scale-codec/std",
	"precompile-utils/std",
	"sp-core/std",
	"sp-io/std",
	"sp-std/std",
	"sp-runtime/std"
]
